/// Flutter icons SpartanIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SpartanIcons
///      fonts:
///       - asset: SpartanIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';


class SpartanIcons {
  SpartanIcons._();

  static const _kFontFam = 'SpartanIcons';
  static const _kFontPkg = null;

  static const IconData search = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vSection = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dForum = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sCart = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
